============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-7.1.2, pluggy-1.0.0 -- /home/artur/repos/silenteight/venv2/bin/python
cachedir: .pytest_cache
rootdir: /home/artur/repos/silenteight/etl-pipeline, configfile: setup.cfg
plugins: asyncio-0.18.3
asyncio: mode=legacy
collecting ... collected 1 item

tests/test_json/test_integration/test_parametrized.py::test_parametrized[notebooks/sample/isg_party_in_payload_format_with_01_entitytype.json-test_lack_of_data_for_geo_agent] 

=============================== warnings summary ===============================
../venv2/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191
  /home/artur/repos/silenteight/venv2/lib/python3.7/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

tests/test_json/test_integration/test_parametrized.py::test_parametrized[notebooks/sample/isg_party_in_payload_format_with_01_entitytype.json-test_lack_of_data_for_geo_agent]
  /home/artur/repos/silenteight/venv2/lib/python3.7/site-packages/consul/base.py:812: DeprecationWarning: Consul 1.4.0 deprecates the legacy ACL.
    DeprecationWarning)

tests/test_json/test_integration/test_parametrized.py::test_parametrized[notebooks/sample/isg_party_in_payload_format_with_01_entitytype.json-test_lack_of_data_for_geo_agent]
  /home/artur/repos/silenteight/venv2/lib/python3.7/site-packages/consul/base.py:2558: DeprecationWarning: 1.6.0+: The discovery chain API is available in Consul versions 1.6.0 and newer.
    'and newer.', DeprecationWarning)

../venv2/lib/python3.7/site-packages/_pytest/cacheprovider.py:433
  /home/artur/repos/silenteight/venv2/lib/python3.7/site-packages/_pytest/cacheprovider.py:433: PytestCacheWarning: cache could not write path /home/artur/repos/silenteight/etl-pipeline/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../venv2/lib/python3.7/site-packages/_pytest/stepwise.py:52
  /home/artur/repos/silenteight/venv2/lib/python3.7/site-packages/_pytest/stepwise.py:52: PytestCacheWarning: cache could not write path /home/artur/repos/silenteight/etl-pipeline/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/artur/repos/silenteight/etl-pipeline/tests/test_json/test_integration/test_parametrized.py:27: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
============================= 5 warnings in 8.08s ==============================
